apiVersion: v1
kind: Secret
metadata:
  name: jobmatcher-secrets
  namespace: jobmatcher
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DB_USERNAME: am9ibWF0Y2hlcg==  # jobmatcher
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  JWT_SECRET: anNlY3JldGtleQ==   # jsecretkey
  REDIS_PASSWORD: ""              # Empty for no password
stringData:
  # Plain text values for easier management
  DB_USERNAME: "jobmatcher"
  DB_PASSWORD: "password123"
  JWT_SECRET: "jsecretkey"
  REDIS_PASSWORD: ""
