FROM python:3.11-slim
WORKDIR /app
COPY parser-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY parser-service/app /app/app
EXPOSE 8080
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8080"]
