version: "3.8"

services:
  # Web Frontend (Users)
  web-frontend:
    build:
      context: ../frontend/web
      dockerfile: Dockerfile
      args:
        VITE_API_AUTH: http://localhost:8081
    container_name: jm-web-frontend
    ports:
      - "4001:80"
    environment:
      - NODE_ENV=production
    networks:
      - jobmatcher-network
    restart: unless-stopped

  # Agent Frontend
  agent-frontend:
    build:
      context: ../frontend/agent
      dockerfile: Dockerfile
      args:
        VITE_API_AUTH: http://localhost:8081
    container_name: jm-agent-frontend
    ports:
      - "4002:80"
    environment:
      - NODE_ENV=production
    networks:
      - jobmatcher-network
    restart: unless-stopped

  # Admin Frontend
  admin-frontend:
    build:
      context: ../frontend/admin
      dockerfile: Dockerfile
      args:
        VITE_API_AUTH: http://localhost:8084
    container_name: jm-admin-frontend
    ports:
      - "4003:80"
    environment:
      - NODE_ENV=production
    networks:
      - jobmatcher-network
    restart: unless-stopped

networks:
  jobmatcher-network:
    external: true
