version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: jm-mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: ["3306:3306"]
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci",
      ]
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: jm-minio-prod
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio_data:/data
    restart: unless-stopped

  nats:
    image: nats:2.10
    container_name: jm-nats-prod
    ports: ["4222:4222", "8222:8222"]
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: jm-gotenberg-prod
    ports: ["3000:3000"]
    restart: unless-stopped

  # --- Go services ---
  auth-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/auth-service:latest
    container_name: jm-auth-prod
    environment:
      - PORT=8080
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  resume-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/resume-service:latest
    container_name: jm-resume-prod
    environment:
      PORT: "8080"
      S3_ENDPOINT: "minio:9000"
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: "resumes"
      NATS_URL: "nats://nats:4222"
      GOTENBERG_URL: "http://gotenberg:3000"
    depends_on: [mysql, minio, nats, gotenberg]
    ports: ["8082:8080"]
    restart: unless-stopped

  job-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/job-service:latest
    container_name: jm-job-prod
    environment:
      PORT: "8080"
      MYSQL_DSN: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
    depends_on: [mysql, nats]
    ports: ["8083:8080"]
    restart: unless-stopped

  pdf-worker:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/pdf-worker:latest
    container_name: jm-pdfworker-prod
    environment:
      NATS_URL: "nats://nats:4222"
      S3_ENDPOINT: "minio:9000"
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: "resumes"
      GOTENBERG_URL: "http://gotenberg:3000"
    depends_on: [nats, minio, gotenberg]
    restart: unless-stopped

  parser-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/parser-service:latest
    container_name: jm-parser-prod
    ports: ["8089:8080"]
    restart: unless-stopped

  admin-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/admin-service:latest
    container_name: jm-admin-prod
    environment:
      - PORT=8080
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8084:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  agent-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/agent-service:latest
    container_name: jm-agent-prod
    environment:
      - PORT=8080
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  company-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/company-service:latest
    container_name: jm-company-prod
    environment:
      - PORT=8080
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
    ports:
      - "8086:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  offer-service:
    image: ${DOCKER_REGISTRY}/jobmatcher-app/offer-service:latest
    container_name: jm-offer-prod
    environment:
      - PORT=8080
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&loc=Local
    ports:
      - "8087:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: jm-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - auth-service
      - resume-service
      - job-service
      - admin-service
      - agent-service
      - company-service
      - offer-service
    restart: unless-stopped

volumes:
  mysql_data:
  minio_data:
